version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/proj1"
    schedule:
      interval: "daily"
    labels:
      - "proj1 dependencies"
      - "mono"

  - package-ecosystem: "npm"
    directory: "/proj2"
    schedule:
      interval: "daily"
    labels:
      - "proj2 dependencies"
      - "mono"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "mono"
    labels:
      - "dependencies"
      - "mono"