version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/proj1"
    schedule:
      interval: "daily"
    labels:
      - "proj1 dependencies"

  - package-ecosystem: "npm"
    directory: "/proj2"
    schedule:
      interval: "daily"
    labels:
      - "proj2 dependencies"
